version: 2.1

workflows:
  test-env-vars:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt
      - run:
          command: |
            echo "hello world" > output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            cat output.txt